# Generated by Django 4.0.3 on 2022-04-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[('1', '1 (worst)'), ('2', '2'), ('3', '3 (indifferent)'), ('4', '4'), ('5', '5 (best)')], default='3', max_length=1)),
                ('foreign_key', models.IntegerField(max_length=4)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
